//Copyright (C) 2016 OLogN Technologies AG

ENCODING("LINEAR-EXTRAPOLATION") PUBLISHABLE_STRUCT TestExtrapolation {

  LINEAR_EXTRAPOLATION tick;
  LINEAR_EXTRAPOLATION(0.01) anInteger;

  LINEAR_EXTRAPOLATION(0.01) aFloat;
  LINEAR_EXTRAPOLATION(0.01) aDouble;

};

