// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: output.proto

#ifndef PROTOBUF_output_2eproto__INCLUDED
#define PROTOBUF_output_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_output_2eproto();
void protobuf_AssignDesc_output_2eproto();
void protobuf_ShutdownFile_output_2eproto();

class Item;
class Character;

enum Character_Animation {
  Character_Animation_Running = 2,
  Character_Animation_Standing = 0,
  Character_Animation_Walking = 1
};
bool Character_Animation_IsValid(int value);
const Character_Animation Character_Animation_Animation_MIN = Character_Animation_Standing;
const Character_Animation Character_Animation_Animation_MAX = Character_Animation_Running;
const int Character_Animation_Animation_ARRAYSIZE = Character_Animation_Animation_MAX + 1;

const ::google::protobuf::EnumDescriptor* Character_Animation_descriptor();
inline const ::std::string& Character_Animation_Name(Character_Animation value) {
  return ::google::protobuf::internal::NameOfEnum(
    Character_Animation_descriptor(), value);
}
inline bool Character_Animation_Parse(
    const ::std::string& name, Character_Animation* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Character_Animation>(
    Character_Animation_descriptor(), name, value);
}
// ===================================================================

class Item : public ::google::protobuf::Message {
 public:
  Item();
  virtual ~Item();

  Item(const Item& from);

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Item& default_instance();

  void Swap(Item* other);

  // implements Message ----------------------------------------------

  Item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:pb.Item)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  friend void  protobuf_AddDesc_output_2eproto();
  friend void protobuf_AssignDesc_output_2eproto();
  friend void protobuf_ShutdownFile_output_2eproto();

  void InitAsDefaultInstance();
  static Item* default_instance_;
};
// -------------------------------------------------------------------

class Character : public ::google::protobuf::Message {
 public:
  Character();
  virtual ~Character();

  Character(const Character& from);

  inline Character& operator=(const Character& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Character& default_instance();

  void Swap(Character* other);

  // implements Message ----------------------------------------------

  Character* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Character& from);
  void MergeFrom(const Character& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Character_Animation Animation;
  static const Animation Running = Character_Animation_Running;
  static const Animation Standing = Character_Animation_Standing;
  static const Animation Walking = Character_Animation_Walking;
  static inline bool Animation_IsValid(int value) {
    return Character_Animation_IsValid(value);
  }
  static const Animation Animation_MIN =
    Character_Animation_Animation_MIN;
  static const Animation Animation_MAX =
    Character_Animation_Animation_MAX;
  static const int Animation_ARRAYSIZE =
    Character_Animation_Animation_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Animation_descriptor() {
    return Character_Animation_descriptor();
  }
  static inline const ::std::string& Animation_Name(Animation value) {
    return Character_Animation_Name(value);
  }
  static inline bool Animation_Parse(const ::std::string& name,
      Animation* value) {
    return Character_Animation_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional uint64 max_u8 = 1;
  inline bool has_max_u8() const;
  inline void clear_max_u8();
  static const int kMaxU8FieldNumber = 1;
  inline ::google::protobuf::uint64 max_u8() const;
  inline void set_max_u8(::google::protobuf::uint64 value);

  // optional uint64 max_u16 = 2;
  inline bool has_max_u16() const;
  inline void clear_max_u16();
  static const int kMaxU16FieldNumber = 2;
  inline ::google::protobuf::uint64 max_u16() const;
  inline void set_max_u16(::google::protobuf::uint64 value);

  // optional uint64 max_u32 = 3;
  inline bool has_max_u32() const;
  inline void clear_max_u32();
  static const int kMaxU32FieldNumber = 3;
  inline ::google::protobuf::uint64 max_u32() const;
  inline void set_max_u32(::google::protobuf::uint64 value);

  // optional sint64 min_s8 = 4;
  inline bool has_min_s8() const;
  inline void clear_min_s8();
  static const int kMinS8FieldNumber = 4;
  inline ::google::protobuf::int64 min_s8() const;
  inline void set_min_s8(::google::protobuf::int64 value);

  // optional sint64 min_s16 = 5;
  inline bool has_min_s16() const;
  inline void clear_min_s16();
  static const int kMinS16FieldNumber = 5;
  inline ::google::protobuf::int64 min_s16() const;
  inline void set_min_s16(::google::protobuf::int64 value);

  // optional sint64 min_s32 = 6;
  inline bool has_min_s32() const;
  inline void clear_min_s32();
  static const int kMinS32FieldNumber = 6;
  inline ::google::protobuf::int64 min_s32() const;
  inline void set_min_s32(::google::protobuf::int64 value);

  // optional sint64 max_s8 = 7;
  inline bool has_max_s8() const;
  inline void clear_max_s8();
  static const int kMaxS8FieldNumber = 7;
  inline ::google::protobuf::int64 max_s8() const;
  inline void set_max_s8(::google::protobuf::int64 value);

  // optional sint64 max_s16 = 8;
  inline bool has_max_s16() const;
  inline void clear_max_s16();
  static const int kMaxS16FieldNumber = 8;
  inline ::google::protobuf::int64 max_s16() const;
  inline void set_max_s16(::google::protobuf::int64 value);

  // optional sint64 max_s32 = 9;
  inline bool has_max_s32() const;
  inline void clear_max_s32();
  static const int kMaxS32FieldNumber = 9;
  inline ::google::protobuf::int64 max_s32() const;
  inline void set_max_s32(::google::protobuf::int64 value);

  // optional double x = 10;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 10;
  inline double x() const;
  inline void set_x(double value);

  // optional double y = 11;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 11;
  inline double y() const;
  inline void set_y(double value);

  // optional double z = 12;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 12;
  inline double z() const;
  inline void set_z(double value);

  // optional double angle = 13;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 13;
  inline double angle() const;
  inline void set_angle(double value);

  // optional .pb.Character.Animation anim = 14;
  inline bool has_anim() const;
  inline void clear_anim();
  static const int kAnimFieldNumber = 14;
  inline ::pb::Character_Animation anim() const;
  inline void set_anim(::pb::Character_Animation value);

  // optional uint64 flag = 15;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 15;
  inline ::google::protobuf::uint64 flag() const;
  inline void set_flag(::google::protobuf::uint64 value);

  // optional string desc = 16;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 16;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // @@protoc_insertion_point(class_scope:pb.Character)
 private:
  inline void set_has_max_u8();
  inline void clear_has_max_u8();
  inline void set_has_max_u16();
  inline void clear_has_max_u16();
  inline void set_has_max_u32();
  inline void clear_has_max_u32();
  inline void set_has_min_s8();
  inline void clear_has_min_s8();
  inline void set_has_min_s16();
  inline void clear_has_min_s16();
  inline void set_has_min_s32();
  inline void clear_has_min_s32();
  inline void set_has_max_s8();
  inline void clear_has_max_s8();
  inline void set_has_max_s16();
  inline void clear_has_max_s16();
  inline void set_has_max_s32();
  inline void clear_has_max_s32();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_angle();
  inline void clear_has_angle();
  inline void set_has_anim();
  inline void clear_has_anim();
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_desc();
  inline void clear_has_desc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 max_u8_;
  ::google::protobuf::uint64 max_u16_;
  ::google::protobuf::uint64 max_u32_;
  ::google::protobuf::int64 min_s8_;
  ::google::protobuf::int64 min_s16_;
  ::google::protobuf::int64 min_s32_;
  ::google::protobuf::int64 max_s8_;
  ::google::protobuf::int64 max_s16_;
  ::google::protobuf::int64 max_s32_;
  double x_;
  double y_;
  double z_;
  double angle_;
  ::google::protobuf::uint64 flag_;
  ::std::string* desc_;
  int anim_;
  friend void  protobuf_AddDesc_output_2eproto();
  friend void protobuf_AssignDesc_output_2eproto();
  friend void protobuf_ShutdownFile_output_2eproto();

  void InitAsDefaultInstance();
  static Character* default_instance_;
};
// ===================================================================


// ===================================================================

// Item

// optional string name = 1;
inline bool Item::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Item::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Item::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Item::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Item::name() const {
  // @@protoc_insertion_point(field_get:pb.Item.name)
  return *name_;
}
inline void Item::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:pb.Item.name)
}
inline void Item::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:pb.Item.name)
}
inline void Item::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pb.Item.name)
}
inline ::std::string* Item::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pb.Item.name)
  return name_;
}
inline ::std::string* Item::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Item::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pb.Item.name)
}

// -------------------------------------------------------------------

// Character

// optional uint64 max_u8 = 1;
inline bool Character::has_max_u8() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Character::set_has_max_u8() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Character::clear_has_max_u8() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Character::clear_max_u8() {
  max_u8_ = GOOGLE_ULONGLONG(0);
  clear_has_max_u8();
}
inline ::google::protobuf::uint64 Character::max_u8() const {
  // @@protoc_insertion_point(field_get:pb.Character.max_u8)
  return max_u8_;
}
inline void Character::set_max_u8(::google::protobuf::uint64 value) {
  set_has_max_u8();
  max_u8_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.max_u8)
}

// optional uint64 max_u16 = 2;
inline bool Character::has_max_u16() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Character::set_has_max_u16() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Character::clear_has_max_u16() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Character::clear_max_u16() {
  max_u16_ = GOOGLE_ULONGLONG(0);
  clear_has_max_u16();
}
inline ::google::protobuf::uint64 Character::max_u16() const {
  // @@protoc_insertion_point(field_get:pb.Character.max_u16)
  return max_u16_;
}
inline void Character::set_max_u16(::google::protobuf::uint64 value) {
  set_has_max_u16();
  max_u16_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.max_u16)
}

// optional uint64 max_u32 = 3;
inline bool Character::has_max_u32() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Character::set_has_max_u32() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Character::clear_has_max_u32() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Character::clear_max_u32() {
  max_u32_ = GOOGLE_ULONGLONG(0);
  clear_has_max_u32();
}
inline ::google::protobuf::uint64 Character::max_u32() const {
  // @@protoc_insertion_point(field_get:pb.Character.max_u32)
  return max_u32_;
}
inline void Character::set_max_u32(::google::protobuf::uint64 value) {
  set_has_max_u32();
  max_u32_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.max_u32)
}

// optional sint64 min_s8 = 4;
inline bool Character::has_min_s8() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Character::set_has_min_s8() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Character::clear_has_min_s8() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Character::clear_min_s8() {
  min_s8_ = GOOGLE_LONGLONG(0);
  clear_has_min_s8();
}
inline ::google::protobuf::int64 Character::min_s8() const {
  // @@protoc_insertion_point(field_get:pb.Character.min_s8)
  return min_s8_;
}
inline void Character::set_min_s8(::google::protobuf::int64 value) {
  set_has_min_s8();
  min_s8_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.min_s8)
}

// optional sint64 min_s16 = 5;
inline bool Character::has_min_s16() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Character::set_has_min_s16() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Character::clear_has_min_s16() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Character::clear_min_s16() {
  min_s16_ = GOOGLE_LONGLONG(0);
  clear_has_min_s16();
}
inline ::google::protobuf::int64 Character::min_s16() const {
  // @@protoc_insertion_point(field_get:pb.Character.min_s16)
  return min_s16_;
}
inline void Character::set_min_s16(::google::protobuf::int64 value) {
  set_has_min_s16();
  min_s16_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.min_s16)
}

// optional sint64 min_s32 = 6;
inline bool Character::has_min_s32() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Character::set_has_min_s32() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Character::clear_has_min_s32() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Character::clear_min_s32() {
  min_s32_ = GOOGLE_LONGLONG(0);
  clear_has_min_s32();
}
inline ::google::protobuf::int64 Character::min_s32() const {
  // @@protoc_insertion_point(field_get:pb.Character.min_s32)
  return min_s32_;
}
inline void Character::set_min_s32(::google::protobuf::int64 value) {
  set_has_min_s32();
  min_s32_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.min_s32)
}

// optional sint64 max_s8 = 7;
inline bool Character::has_max_s8() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Character::set_has_max_s8() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Character::clear_has_max_s8() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Character::clear_max_s8() {
  max_s8_ = GOOGLE_LONGLONG(0);
  clear_has_max_s8();
}
inline ::google::protobuf::int64 Character::max_s8() const {
  // @@protoc_insertion_point(field_get:pb.Character.max_s8)
  return max_s8_;
}
inline void Character::set_max_s8(::google::protobuf::int64 value) {
  set_has_max_s8();
  max_s8_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.max_s8)
}

// optional sint64 max_s16 = 8;
inline bool Character::has_max_s16() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Character::set_has_max_s16() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Character::clear_has_max_s16() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Character::clear_max_s16() {
  max_s16_ = GOOGLE_LONGLONG(0);
  clear_has_max_s16();
}
inline ::google::protobuf::int64 Character::max_s16() const {
  // @@protoc_insertion_point(field_get:pb.Character.max_s16)
  return max_s16_;
}
inline void Character::set_max_s16(::google::protobuf::int64 value) {
  set_has_max_s16();
  max_s16_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.max_s16)
}

// optional sint64 max_s32 = 9;
inline bool Character::has_max_s32() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Character::set_has_max_s32() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Character::clear_has_max_s32() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Character::clear_max_s32() {
  max_s32_ = GOOGLE_LONGLONG(0);
  clear_has_max_s32();
}
inline ::google::protobuf::int64 Character::max_s32() const {
  // @@protoc_insertion_point(field_get:pb.Character.max_s32)
  return max_s32_;
}
inline void Character::set_max_s32(::google::protobuf::int64 value) {
  set_has_max_s32();
  max_s32_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.max_s32)
}

// optional double x = 10;
inline bool Character::has_x() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Character::set_has_x() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Character::clear_has_x() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Character::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Character::x() const {
  // @@protoc_insertion_point(field_get:pb.Character.x)
  return x_;
}
inline void Character::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.x)
}

// optional double y = 11;
inline bool Character::has_y() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Character::set_has_y() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Character::clear_has_y() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Character::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Character::y() const {
  // @@protoc_insertion_point(field_get:pb.Character.y)
  return y_;
}
inline void Character::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.y)
}

// optional double z = 12;
inline bool Character::has_z() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Character::set_has_z() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Character::clear_has_z() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Character::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Character::z() const {
  // @@protoc_insertion_point(field_get:pb.Character.z)
  return z_;
}
inline void Character::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.z)
}

// optional double angle = 13;
inline bool Character::has_angle() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Character::set_has_angle() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Character::clear_has_angle() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Character::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline double Character::angle() const {
  // @@protoc_insertion_point(field_get:pb.Character.angle)
  return angle_;
}
inline void Character::set_angle(double value) {
  set_has_angle();
  angle_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.angle)
}

// optional .pb.Character.Animation anim = 14;
inline bool Character::has_anim() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Character::set_has_anim() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Character::clear_has_anim() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Character::clear_anim() {
  anim_ = 2;
  clear_has_anim();
}
inline ::pb::Character_Animation Character::anim() const {
  // @@protoc_insertion_point(field_get:pb.Character.anim)
  return static_cast< ::pb::Character_Animation >(anim_);
}
inline void Character::set_anim(::pb::Character_Animation value) {
  assert(::pb::Character_Animation_IsValid(value));
  set_has_anim();
  anim_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.anim)
}

// optional uint64 flag = 15;
inline bool Character::has_flag() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Character::set_has_flag() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Character::clear_has_flag() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Character::clear_flag() {
  flag_ = GOOGLE_ULONGLONG(0);
  clear_has_flag();
}
inline ::google::protobuf::uint64 Character::flag() const {
  // @@protoc_insertion_point(field_get:pb.Character.flag)
  return flag_;
}
inline void Character::set_flag(::google::protobuf::uint64 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:pb.Character.flag)
}

// optional string desc = 16;
inline bool Character::has_desc() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void Character::set_has_desc() {
  _has_bits_[0] |= 0x00008000u;
}
inline void Character::clear_has_desc() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void Character::clear_desc() {
  if (desc_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& Character::desc() const {
  // @@protoc_insertion_point(field_get:pb.Character.desc)
  return *desc_;
}
inline void Character::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
  // @@protoc_insertion_point(field_set:pb.Character.desc)
}
inline void Character::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
  // @@protoc_insertion_point(field_set_char:pb.Character.desc)
}
inline void Character::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pb.Character.desc)
}
inline ::std::string* Character::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pb.Character.desc)
  return desc_;
}
inline ::std::string* Character::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Character::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pb.Character.desc)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pb::Character_Animation> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pb::Character_Animation>() {
  return ::pb::Character_Animation_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_output_2eproto__INCLUDED
