#line 26 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT Limit {
_Bool inclusive;
double value;
};

#line 31 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT Location {
string fileName;
int32_t lineNumber;
};

#line 36 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT CharacterRange {

uint32_t from;
uint32_t to;
};

#line 45 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT CharacterSet {

vector<CharacterRange> ranges;
};

#line 50 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT Variant {


enum KIND {IDENTIFIER( "NONE" ) = 0,IDENTIFIER( "NUMBER" ) = 1,IDENTIFIER( "STRING" ) = 2} kind;

double numberValue;
string stringValue;
};

#line 63 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT DataType {





enum KIND {IDENTIFIER( "ENUM" ) = 0,IDENTIFIER( "NAMED_TYPE" ) = 1,IDENTIFIER( "SEQUENCE" ) = 2,IDENTIFIER( "ENCODING_SPECIFIC" ) = 3,IDENTIFIER( "MAPPING_SPECIFIC" ) = 4,IDENTIFIER( "INTEGER" ) = 5,IDENTIFIER( "FIXED_POINT" ) = 6,IDENTIFIER( "FLOATING_POINT" ) = 7,IDENTIFIER( "CHARACTER" ) = 8,IDENTIFIER( "CHARACTER_STRING" ) = 9,IDENTIFIER( "BIT_STRING" ) = 10,IDENTIFIER( "DICTIONARY" ) = 11,IDENTIFIER( "DISCRIMINATED_UNION" ) = 12} kind;
string name;
string mappingName;
string encodingName;
unique_ptr<DataType> keyType;
unique_ptr<DataType> paramType;
Limit lowLimit;
Limit highLimit;
double fixedPrecision;
uint8_t floatingSignificandBits;
uint8_t floatingExponentBits;
CharacterSet characterSet;
uint32_t stringMinSize;
uint32_t stringMaxSize;

map<string, Variant> encodingAttrs;
map<string, Variant> mappingAttrs;
map<string, uint32_t> enumValues;

};

#line 118 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT EncodingSpecifics {


string name;
map<string, Variant> attrs;
};

#line 126 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT EncodedOrMember {


Location location;
};

#line 133 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT DataMember {


DataType type;
string name;
_Bool extendTo;
Variant defaultValue;
vector<string> whenDiscriminant;
};

#line 143 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT EncodedMembers {


EncodingSpecifics encodingSpecifics;
vector<unique_ptr<EncodedOrMember> > members;
};

#line 151 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT Structure {




enum DECLTYPE {IDENTIFIER( "IDL" ) = 0,IDENTIFIER( "MAPPING" ) = 1,IDENTIFIER( "ENCODING" ) = 2} declType;
enum TYPE {IDENTIFIER( "STRUCT" ) = 0,IDENTIFIER( "RPC" ) = 1,IDENTIFIER( "DISCRIMINATED_UNION" ) = 2} type;
string name;
string discriminant;
string inheritedFrom;
};

#line 165 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT Typedef {

Location location;
DataType type;
string name;
};

#line 172 "C:\Projects\o-log-n\Hare-IDL\dbg\front\idl\..\..\..\src\front-back\idl_tree.h";
MAPPING( FrontEnd="1.0") PUBLISHABLE-STRUCT Root {


vector<Typedef> typedefs;
vector<unique_ptr<Structure> > structures;
};

